<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-32AS404" ignored="0" name="Retry multiple failed test case" tests="9" failures="2" timestamp="14 Jan 2019 13:27:20 GMT" time="0.071" errors="0">
  <testcase name="test1" time="0.009" classname="TESTNGBasic.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="TESTNGBasic.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="TESTNGBasic.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="TESTNGBasic.RetryLogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TESTNGBasic.RetryLogicTest.test1(RetryLogicTest.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.001" classname="TESTNGBasic.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="TESTNGBasic.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="TESTNGBasic.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="TESTNGBasic.RetryLogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TESTNGBasic.RetryLogicTest.test2(RetryLogicTest.java:15)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.002" classname="TESTNGBasic.RetryLogicTest"/>
</testsuite> <!-- Retry multiple failed test case -->
